/**
 * types.ts - TypeScript interfaces for slide manifest and viewer configuration
 */

/**
 * Slide manifest generated by the tiler (manifest.json)
 */
export interface SlideManifest {
  slide_id: string;
  level0_width: number;
  level0_height: number;
  mpp0: number;  // Microns per pixel at level 0
  patch_px: number;  // Patch size in pixels (256 or 512)
  tile_size: number;  // Tile size used for DZI generation
  overlap: number;  // Tile overlap (should be 0)
  anchor: [number, number];  // Grid anchor point (should be [0, 0])
  alignment_ok: boolean;  // Whether alignment check passed
  created_at: string;  // ISO 8601 timestamp
  dzi_level_count: number;  // Number of DZI pyramid levels
  magnification_levels: {
    '40x': number;   // DZI level index for 40× magnification
    '20x': number;   // DZI level index for 20× magnification
    '10x': number;   // DZI level index for 10× magnification
    '5x': number;    // DZI level index for 5× magnification
    '2.5x': number;  // DZI level index for 2.5× magnification
  };
}

/**
 * Current viewer state for grid rendering
 */
export interface GridState {
  manifest: SlideManifest;
  currentZoomMag: number;  // Current magnification (2.5, 5, 10, 20, or 40)
  currentDziLevel: number;  // Current DZI level index being viewed
  cellSize: number;  // Current cell size in level-0 pixels
  numCols: number;  // Number of complete columns
  numRows: number;  // Number of complete rows
}

/**
 * Zoom history entry for Back/Reset functionality
 */
export interface ZoomHistoryEntry {
  zoomMag: number;  // Magnification level (2.5, 5, 10, 20, 40) or placeholder for fit mode
  centerX: number;  // Center X in level-0 coordinates
  centerY: number;  // Center Y in level-0 coordinates
}

/**
 * Event types for logging user interactions
 */
export type EventType = 
  | 'app_start'
  | 'slide_load'
  | 'cell_click'
  | 'zoom_step'
  | 'arrow_pan'
  | 'back_step'
  | 'reset'
  | 'label_select'
  | 'slide_next';

/**
 * Log event matching CSV schema from spec
 */
export interface LogEvent {
  ts_iso8601: string;       // ISO 8601 timestamp
  session_id: string;       // Session UUID
  user_id: string;          // User identifier (placeholder in V1)
  slide_id: string;         // Slide identifier from manifest
  event: EventType;         // Event type
  zoom_level: number;       // Current magnification (2.5, 5, 10, 20, or 40)
  dzi_level: number;        // DZI pyramid level index (14, 15, 16, 17, or 18)
  i: number | null;         // Grid cell column index (null if not applicable)
  j: number | null;         // Grid cell row index (null if not applicable)
  center_x0: number;        // Viewport center X in level-0 coords
  center_y0: number;        // Viewport center Y in level-0 coords
  vbx0: number;             // Viewport bottom-left X in level-0
  vby0: number;             // Viewport bottom-left Y in level-0
  vtx0: number;             // Viewport top-right X in level-0
  vty0: number;             // Viewport top-right Y in level-0
  container_w: number;      // Container width in pixels
  container_h: number;      // Container height in pixels
  dpr: number;              // Device pixel ratio
  patch_px: number;         // Patch size from manifest
  tile_size: number;        // Tile size from manifest
  alignment_ok: boolean;    // Alignment check status from manifest
  app_version: string;      // Application version
  label?: string;           // Label value (for label_select events)
}

