/**
 * types.ts - TypeScript interfaces for slide manifest and viewer configuration
 */

/**
 * Slide manifest generated by the tiler (manifest.json)
 */
export interface SlideManifest {
  slide_id: string;
  level0_width: number;
  level0_height: number;
  mpp0: number;  // Microns per pixel at level 0
  patch_px: number;  // Patch size in pixels (256 or 512)
  tile_size: number;  // Tile size used for DZI generation
  overlap: number;  // Tile overlap (should be 0)
  anchor: [number, number];  // Grid anchor point (should be [0, 0])
  alignment_ok: boolean;  // Whether alignment check passed
  created_at: string;  // ISO 8601 timestamp
  dzi_level_count: number;  // Number of DZI pyramid levels
  magnification_levels: {
    '40x': number;   // DZI level index for 40× magnification
    '20x': number;   // DZI level index for 20× magnification
    '10x': number;   // DZI level index for 10× magnification
    '5x': number;    // DZI level index for 5× magnification
    '2.5x': number;  // DZI level index for 2.5× magnification
  };
}

/**
 * Current viewer state for zoom tracking
 * Note: Cell/grid fields removed - we now track exact click coordinates only
 */
export interface ViewerState {
  manifest: SlideManifest;
  currentZoomMag: number;  // Current magnification (2.5, 5, 10, 20, or 40)
  currentDziLevel: number;  // Current DZI level index being viewed
}

/**
 * Zoom history entry for Back/Reset functionality
 */
export interface ZoomHistoryEntry {
  zoomMag: number;  // Magnification level (2.5, 5, 10, 20, 40) or placeholder for fit mode
  centerX: number;  // Center X in level-0 coordinates
  centerY: number;  // Center Y in level-0 coordinates
}

/**
 * Event types for logging user interactions
 */
export type EventType = 
  | 'app_start'
  | 'slide_load'
  | 'cell_click'
  | 'zoom_step'
  | 'arrow_pan'
  | 'back_step'
  | 'reset'
  | 'label_select'
  | 'slide_next';

/**
 * Log event - captures user interaction with full viewport state
 * All coordinates are in level-0 (full resolution) pixel space
 */
export interface LogEvent {
  ts_iso8601: string;       // ISO 8601 timestamp
  session_id: string;       // Session UUID
  user_id: string;          // User identifier
  slide_id: string;         // Slide identifier from manifest
  event: EventType;         // Event type
  zoom_level: number;       // Current magnification (2.5, 5, 10, 20, or 40) or actual for fit mode
  dzi_level: number;        // DZI pyramid level index (actual level being rendered)
  click_x0: number | null;  // Exact click X in level-0 coords (only for cell_click)
  click_y0: number | null;  // Exact click Y in level-0 coords (only for cell_click)
  center_x0: number;        // Viewport center X in level-0 coords
  center_y0: number;        // Viewport center Y in level-0 coords
  vbx0: number;             // Viewport bottom-left X in level-0
  vby0: number;             // Viewport bottom-left Y in level-0
  vtx0: number;             // Viewport top-right X in level-0
  vty0: number;             // Viewport top-right Y in level-0
  container_w: number;      // Container width in pixels
  container_h: number;      // Container height in pixels
  dpr: number;              // Device pixel ratio
  app_version: string;      // Application version
  label?: string;           // Label value (for label_select events)
  notes?: string | null;    // Notes captured with slide completion
  viewing_attempt: number;  // Which viewing attempt this event belongs to (1 = first, 2+ = resumed)
}

// ============================================================================
// V2 Multi-User Types (Backend API Integration)
// ============================================================================

/**
 * User information from authentication
 */
export interface User {
  id: string;           // UUID from database
  username: string;     // Username for login
  role: string;         // 'pathologist' or 'admin'
}

/**
 * Slide information from backend API
 * Different from SlideManifest - this includes completion status
 */
export interface Slide {
  id: string;                   // UUID from database
  slide_id: string;             // Slide identifier (e.g., "test_slide")
  s3_key_prefix: string;        // S3 path prefix for tiles
  completed: boolean;           // Whether this user has completed this slide
  session_id: string | null;    // Session UUID if started, null if not
  label: string | null;         // Label if completed ('normal' | 'benign' | 'malignant')
  started_at?: string | null;   // ISO timestamp when session started
  completed_at?: string | null; // ISO timestamp when session completed
}

/**
 * Session information from backend API
 */
export interface Session {
  id: string;           // Session UUID
  slide_id: string;     // Slide identifier
  started_at: string;   // ISO timestamp when session started
  completed_at?: string | null; // ISO timestamp when completed
  label?: string | null;        // Label if completed
}

/**
 * Generic API response wrapper for successful responses
 */
export interface APIResponse<T> {
  data: T;
}

/**
 * API error response
 */
export interface APIError {
  error: string;
}

// ============================================================================
// Admin Dashboard Types
// ============================================================================

/**
 * User statistics for admin dashboard
 */
export interface UserStats {
  id: string;              // User UUID
  username: string;        // Username
  total_sessions: number;  // Total sessions started
  completed_sessions: number; // Completed sessions
}

/**
 * Overall study progress statistics
 */
export interface ProgressStats {
  total_pathologists: number;  // Total pathologist users
  total_slides: number;         // Total slides in database
  total_sessions: number;       // Total possible sessions (pathologists × slides)
  completed_sessions: number;   // Total completed sessions
}

// ============================================================================
// Session Replay Types
// ============================================================================

/**
 * Completed session summary for admin dropdown
 */
export interface CompletedSession {
  id: string;              // Session UUID
  user_id: string;         // User UUID
  username: string;        // Username for display
  slide_id: string;        // Slide UUID
  slide_name: string;      // Slide identifier (e.g., "test_slide")
  started_at: string;      // ISO timestamp when session started
  completed_at: string;    // ISO timestamp when completed
  label: string;           // Final diagnosis ('normal' | 'benign' | 'malignant')
  event_count: number;     // Total events in this session
}

/**
 * Event data from backend for replay (matches LogEvent structure)
 * All coordinates are in level-0 (full resolution) pixel space
 */
export interface ReplayEvent {
  id: string;              // Event UUID
  ts_iso8601: string;      // ISO 8601 timestamp
  event: string;           // Event type
  zoom_level: number | null;  // Magnification (2.5, 5, 10, 20, 40)
  dzi_level: number | null;   // DZI pyramid level
  click_x0: number | null;    // Exact click X in level-0 (only for cell_click)
  click_y0: number | null;    // Exact click Y in level-0 (only for cell_click)
  center_x0: number | null;   // Viewport center X (level-0)
  center_y0: number | null;   // Viewport center Y (level-0)
  vbx0: number | null;        // Viewport bottom-left X
  vby0: number | null;        // Viewport bottom-left Y
  vtx0: number | null;        // Viewport top-right X
  vty0: number | null;        // Viewport top-right Y
  container_w: number | null; // Container width
  container_h: number | null; // Container height
  dpr: number | null;         // Device pixel ratio
  app_version: string | null;
  label: string | null;
  notes: string | null;
  viewing_attempt: number;    // Which viewing attempt (1 = first, 2+ = resumed)
}

/**
 * Session metadata for replay
 */
export interface SessionReplayMetadata {
  id: string;              // Session UUID
  user_id: string;         // User UUID
  username: string;        // Username
  slide_id: string;        // Slide UUID  
  slide_name: string;      // Slide identifier
  manifest: SlideManifest; // Full slide manifest for DZI loading
  started_at: string;      // Session start time
  completed_at: string;    // Session completion time
  label: string;           // Final diagnosis
}

/**
 * Complete replay data returned from backend
 */
export interface SessionReplayData {
  session: SessionReplayMetadata;
  events: ReplayEvent[];
}

